### ISSUE TITLE
Mock-ups

### ISSUE THREAD

**Issue by Ananas97** [Ananas97/CodeMeasurement#10]
Prepare mock-ups so we would have the same idea of UI, to ensure integrity

**Comment by Ananas97** [comment]
https://www.figma.com/

**Comment by Ananas97** [comment]
https://www.figma.com/file/28qLDI7xowhQdJX3tTmphv/METRICS-VIEW?node-id=27%3A33

**Comment by Ananas97** [comment]
![image](https://user-images.githubusercontent.com/23456385/80212746-5a548300-8638-11ea-92bf-e8977185d00c.png)
![image](https://user-images.githubusercontent.com/23456385/80212849-8bcd4e80-8638-11ea-9933-049f8ce605de.png)

**Comment by KacMac** [comment]
Love it!
