### ISSUE TITLE
Storing historic code metrics in database - create model

### ISSUE THREAD

**Issue by sorwat** [Ananas97/CodeMeasurement#15]
#2

**Comment by KacMac** [comment]
Relational scheme:
![obraz](https://user-images.githubusercontent.com/22129082/79235253-aac72600-7e6b-11ea-982c-5754ffaa8adb.png)

**Comment by KacMac** [comment]
And logical: 
![obraz](https://user-images.githubusercontent.com/22129082/79235324-bfa3b980-7e6b-11ea-9a11-ad63b98f821c.png)

**Comment by KacMac** [comment]
> 
> 
> Relational scheme:
> ![obraz](https://user-images.githubusercontent.com/22129082/79235253-aac72600-7e6b-11ea-982c-5754ffaa8adb.png)
> 
> Scheme was created in Oracle software so datatypes names can be different in our database

For method metrics there is a bug: Primary Key is just method_name, update_date and class_id. There are no email fields and project_source_name

**Comment by sorwat** [comment]
I have a suggestion for model improvement

**Comment by KacMac** [comment]
Here goes improved model:
![obraz](https://user-images.githubusercontent.com/22129082/80867864-d5501600-8c96-11ea-8b66-b7489089bd74.png)

**Comment by KacMac** [comment]
![obraz](https://user-images.githubusercontent.com/22129082/80867904-295afa80-8c97-11ea-9e65-96a51d88a8f0.png)
