### ISSUE TITLE
Azure configuration 

### ISSUE THREAD

**Issue by Ananas97** [Ananas97/CodeMeasurement#34]
https://www.c-sharpcorner.com/article/creating-asp-net-web-app-in-azure/?fbclid=IwAR3j4xNt9bPuzBELqkKu-lRNIYbHMkA09MQXPFOT-xqjqcwvHPcSxptch1A

**Comment by sorwat** [comment]
TODO:
- [ ] each member should be invited 
(@KacMac  and @pmyszkowski register on https://dev.azure.com/ and write here emails so @Ananas97  can invite you)
- [ ] after each merge to master and feature branch (to be added after first release) app should be build, tests are run and app is deployed

**Comment by KacMac** [comment]
I've created an account on put email (kacper.j.maciejewski...)

**Comment by Ananas97** [comment]
collaboraters to azure cannot be added (ref screenshot)(the steps to solve the issue are as follows verify that your user account is authorized to invite external users under Azure Active Directory > User settings > External users > Manage external collaboration settings but I have no access to the Azure Active Directory to do so so it cannot be done), I've created a new organization: https://dev.azure.com/TSD-Project
![image](https://user-images.githubusercontent.com/23456385/81573708-205bde80-93a5-11ea-8499-ebe43fa3ecaf.png)
